feat(minirum): allow increasing the sampling rate up to 1/10 for specific use cases
adobe/helix-rum-js pull request #159
Opened 2024-05-29 23:20 UTC by ramboz

This introduces a new global variable, `window.RUM_SAMPLING_RATE`, that can be set before loading the library to increase the sampling rate for specific use cases that require more data collected for short-term reporting.
For instance:
- when running an experiment in a 2-week time-frame and achieve statistical significance even with low traffic
- when running short-lived marketing campaign and wanting to collect enough data over a single weekend

## Usage

For instance:
```js
window.RUM_SAMPLING_RATE = 10;
```

Or in an HTML context:
```html
  <head>
    <meta name="experiment" content="Foo"/>
    <meta name="experiment-variants" content="/bar,/baz"/>
    <script>window.RUM_SAMPLING_RATE = document.head.querySelector('meta[name="experiment"]') ? 10 : 100</script>
    <script src="/scripts/aem.js" type="module"></script>
    <script src="/scripts/scripts.js" type="module"></script>
    <link rel="stylesheet" href="/styles/styles.css">
  </head>
```
## Related Issues

Fix #156

2024-05-31 08:57 UTC, chicharr submitted a review, later dismissed

2024-06-05 17:22 UTC, trieloff requested changes

2024-06-05 17:22 UTC, trieloff commented on src/index.js
> +      const weight = new URLSearchParams(window.location.search).get('rum') === 'on' ? 1 : defaultWeight;
```suggestion
      const weight = (window.SAMPLE_PAGEVIEWS_AT_RATE === 'high' && 10) ||
        (window.SAMPLE_PAGEVIEWS_AT_RATE === 'low' && 1000) ||
        (new URLSearchParams(window.location.search).get('rum') === 'on' && 1) ||
        100;
```

2024-06-05 17:23 UTC, trieloff commented
See https://cq-dev.slack.com/archives/C07198KKQ07/p1717543808221569

2024-06-10 10:12 UTC, trieloff commented
Thank you @ramboz. I've added you as a writer to the repository, so you don't need to work off your own fork anymore. On the flip side, please make sure that the change is covered by tests.

2024-06-10 10:13 UTC, trieloff reviewed
Looks good, needs accompanying test.

2024-07-03 09:49 UTC, trieloff commented
Please merge once the conflicts have been resolved.

2024-07-10 14:29 UTC, ramboz commented
@trieloff Properly rebased this against the latest `main`… but I'll need you to re-review before I can actually merge

2024-08-16 10:14 UTC, trieloff approved these changes

2024-08-19 17:19 UTC, merged